# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifier_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(493, 323)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 6, 451, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_quitter_dialog = QtWidgets.QPushButton(self.layoutWidget)
        self.button_quitter_dialog.setObjectName("button_quitter_dialog")
        self.horizontalLayout.addWidget(self.button_quitter_dialog)
        self.button_enregistrer_dialog = QtWidgets.QPushButton(self.layoutWidget)
        self.button_enregistrer_dialog.setObjectName("button_enregistrer_dialog")
        self.horizontalLayout.addWidget(self.button_enregistrer_dialog)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.table_variables_dialog = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_variables_dialog.setObjectName("table_variables_dialog")
        self.table_variables_dialog.setColumnCount(2)
        self.table_variables_dialog.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_variables_dialog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_variables_dialog.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.table_variables_dialog)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_quitter_dialog.setText(_translate("Dialog", "Quitter"))
        self.button_enregistrer_dialog.setText(_translate("Dialog", "Enregister"))
        self.label.setText(_translate("Dialog", "Liste des variables : "))
        item = self.table_variables_dialog.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Inclure"))
        item = self.table_variables_dialog.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Variable"))
