# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_freq_conso.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 372)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.combo_type_conso = QtWidgets.QComboBox(Dialog)
        self.combo_type_conso.setObjectName("combo_type_conso")
        self.horizontalLayout.addWidget(self.combo_type_conso)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.table_mods_pharma = QtWidgets.QTableWidget(Dialog)
        self.table_mods_pharma.setObjectName("table_mods_pharma")
        self.table_mods_pharma.setColumnCount(2)
        self.table_mods_pharma.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_mods_pharma.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_mods_pharma.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.table_mods_pharma)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.button_annuler_conso = QtWidgets.QPushButton(Dialog)
        self.button_annuler_conso.setObjectName("button_annuler_conso")
        self.horizontalLayout_2.addWidget(self.button_annuler_conso)
        self.button_enregistrer_conso = QtWidgets.QPushButton(Dialog)
        self.button_enregistrer_conso.setObjectName("button_enregistrer_conso")
        self.horizontalLayout_2.addWidget(self.button_enregistrer_conso)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Veuillez choisir la matrice de consommation à calculer :"))
        self.label_2.setText(_translate("Dialog", "Modalités à convertir en PHARMACIE :"))
        item = self.table_mods_pharma.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Inclure"))
        item = self.table_mods_pharma.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Modalité"))
        self.button_annuler_conso.setText(_translate("Dialog", "Annuler"))
        self.button_enregistrer_conso.setText(_translate("Dialog", "Enregistrer"))
