# Code de l'interface généré par Qt Designer, sera importé comme module dans le script "script_interface.py"

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 1031, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.VL_indices = QtWidgets.QVBoxLayout()
        self.VL_indices.setObjectName("VL_indices")
        self.variables_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.variables_table.setObjectName("variables_table")
        self.variables_table.setColumnCount(2)
        self.variables_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.variables_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.variables_table.setHorizontalHeaderItem(1, item)
        self.variables_table.horizontalHeader().setDefaultSectionSize(200)
        self.VL_indices.addWidget(self.variables_table)
        self.button_enregistrer = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_enregistrer.sizePolicy().hasHeightForWidth())
        self.button_enregistrer.setSizePolicy(sizePolicy)
        self.button_enregistrer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_enregistrer.setObjectName("button_enregistrer")
        self.VL_indices.addWidget(self.button_enregistrer)
        self.button_annuler = QtWidgets.QPushButton(self.layoutWidget)
        self.button_annuler.setObjectName("pushButton")
        self.VL_indices.addWidget(self.button_annuler)
        self.gridLayout.addLayout(self.VL_indices, 0, 1, 1, 1)
        self.VL_apercu = QtWidgets.QVBoxLayout()
        self.VL_apercu.setObjectName("VL_apercu")
        self.label_apercu = QtWidgets.QLabel(self.layoutWidget)
        self.label_apercu.setObjectName("label_apercu")
        self.VL_apercu.addWidget(self.label_apercu)
        self.table_apercu = QtWidgets.QTableView(self.layoutWidget)
        self.table_apercu.setObjectName("table_apercu")
        self.VL_apercu.addWidget(self.table_apercu)
        self.gridLayout.addLayout(self.VL_apercu, 1, 0, 1, 2)
        self.GL_ajouter = QtWidgets.QGridLayout()
        self.GL_ajouter.setObjectName("GL_ajouter")
        self.button_selectionner = QtWidgets.QPushButton(self.layoutWidget)
        self.button_selectionner.setObjectName("button_selectionner")
        self.GL_ajouter.addWidget(self.button_selectionner, 3, 0, 1, 1)
        self.bases_table = QtWidgets.QTableWidget(self.layoutWidget)
        self.bases_table.setObjectName("bases_table")
        self.bases_table.setColumnCount(3)
        self.bases_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bases_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bases_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bases_table.setHorizontalHeaderItem(2, item)
        self.bases_table.horizontalHeader().setDefaultSectionSize(150)
        self.bases_table.verticalHeader().setVisible(True)
        self.bases_table.verticalHeader().setDefaultSectionSize(30)
        self.GL_ajouter.addWidget(self.bases_table, 0, 0, 2, 1)
        self.button_ajouter_base = QtWidgets.QPushButton(self.layoutWidget)
        self.button_ajouter_base.setObjectName("button_ajouter_base")
        self.GL_ajouter.addWidget(self.button_ajouter_base, 2, 0, 1, 1)
        self.button_supprimer = QtWidgets.QPushButton(self.layoutWidget)
        self.button_supprimer.setObjectName("button_supprimer")
        self.GL_ajouter.addWidget(self.button_supprimer, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.GL_ajouter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.variables_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Colonne"))
        item = self.variables_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Variable"))
        self.button_enregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.button_annuler.setText(_translate("MainWindow", "Annuler"))
        self.label_apercu.setText(_translate("MainWindow", "Apercu de la base selectionnee :"))
        self.button_selectionner.setText(_translate("MainWindow", "Sélectionner"))
        item = self.bases_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fichier"))
        item = self.bases_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Etat"))
        item = self.bases_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type de la base"))
        self.button_ajouter_base.setText(_translate("MainWindow", "Ajouter une base"))
        self.button_supprimer.setText(_translate("MainWindow", "Supprimer"))

